### ISSUE TITLE
Secret credential helper

### ISSUE THREAD

**Issue by clarkbw** [clarkbw/setup-docker#6]
To prevent the credentials from actually being written out to disk we need a credential helper installed and configure. Docker has many options https://docs.docker.com/engine/reference/commandline/login/#credentials-store but those would each need to be installed on the VM being used.  Instead I believe we can use the Actions secret store and offer our own credential helper.

### Current configuration

Right now we pass the password on Docker and it gets stored into the `config.json` with this helpful warning.
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in .docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

```yaml
- uses: clarkbw/setup-docker@v1
  with:
    username: $GITHUB_ACTOR
    password: ${{ secrets.GITHUB_TOKEN }}
    registry: docker.pkg.github.com
```

### Using Actions Secret store

If instead we registered our own custom credentials helper that could only pull credentials from the Actions secret store we could provide a secure mechanism to pass credentials over to Docker without having to write them out to disk.

```yaml
- uses: clarkbw/setup-docker@v1
  with:
    username: $GITHUB_ACTOR
    secret: GITHUB_TOKEN
    registry: docker.pkg.github.com
```

By registering the `secret` name we create an entry for our custom credential helper to lookup the secret value. 

Our system needs to register the name `secretservice` in the path. Run the command `core.addPath('/path/to/secretservice');`

We only need to respond to the `get` command by passing JSON data we received from our yaml setup plus the token from the secret store, in the above example `${{ secrets.GITHUB_TOKEN }}`  

```js
const github = require('@actions/github');
return { Username: username, Secret: github.actions.getRepoSecret({
  owner,
  repo,
  GITHUB_TOKEN,
})};
```

Returning in the format:

```json
{
  "Username": "david",
  "Secret": "passw0rd1"
}
```
